version: '3.8'

services:
  front-end:
    image: node
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
    command: serve -s -l 5000 build

  back-end:
      image: go
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
      ports:
        - 8080:8080
      command: ./server

